Ignis: Latent Dirichlet Allocation
============

In [1]:
import ignis

In [2]:
# Python setup: Note that the `PYTHONHASHSEED` environmental variable needs to be set *before* the Python kernel is intialised --
# We only print it here for easy post-hoc reference.
import os
os.environ.get("PYTHONHASHSEED")

'11399'

In [3]:
# Jupyter notebook setup
import ipywidgets as widgets
from IPython.core.display import display, HTML

# Custom styling:
# - Prevent vertical scrollbars in output subareas
# - Resize to fit pyLDAvis visualisations without causing other cells to overflow
style = """
<style>
   .jupyter-widgets-output-area .output_scroll {
        height: unset !important;
        border-radius: unset !important;
        -webkit-box-shadow: unset !important;
        box-shadow: unset !important;
    }
    .jupyter-widgets-output-area  {
        height: auto !important;
    }
</style>
<style>
    #notebook-container { width: 1370px !important; }
    div.output_area { width: unset !important; }
</style>
"""
display(HTML(style))

Model training (LDA)
----

Load from an `ignis.Corpus`, add the processed docs to an LDA model, and train it.

The random seed and parallelisation can both affect results, so setting the seed and number of workers is necessary for reproducibility.

In [4]:
corpus = ignis.load_corpus("bbc-full.corpus")

In [5]:
model_options = {
    "k": 6,
    "term_weighting": "idf",
    "until_max_ll": False,
    "verbose": True,
    "seed": 7157,
}
vis_options = {"verbose": True}
results = ignis.train_model(
    corpus,
    model_type="tp_lda",
    model_options=model_options,
    vis_type="pyldavis",
    vis_options=vis_options,
)

Training LDA model on 2122 documents:
{'term_weighting': 'idf', 'k': 6, 'seed': 7157, 'workers': 8, 'parallel_scheme': 'default', 'iterations': 1000, 'update_every': 100, 'until_max_ll': False, 'max_extra_iterations': 5000, 'verbose': True, 'tw': <TermWeight.IDF: 1>, 'parallel': <ParallelScheme.DEFAULT: 0>}



100%|██████████| 1000/1000 [00:16<00:00, 60.57it/s, Log-likelihood=-21.11047]

Model training complete. (16.517s)
Preparing LDA visualisation


C:\Users\zechy.wong.ke\Anaconda3\envs\topic-modelling\lib\site-packages\pandas\core\frame.py:7476: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  elif isinstance(data[0], collections.Mapping):


 . . Done. (2.735s)


C:\Users\zechy.wong.ke\Anaconda3\envs\topic-modelling\lib\site-packages\pyLDAvis\_prepare.py:257: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  return pd.concat([default_term_info] + list(topic_dfs))


In [6]:
results.show_visualisation()

In [7]:
model = results.ignis_model.model

doc_topic_dists = [model.docs[n].get_topic_dist() for n in range(len(model.docs))]
doc_lengths = [len(model.docs[n].words) for n in range(len(model.docs))]
vocab = model.vocabs
term_frequency = model.vocab_freq

In [8]:
import pandas as pd
import numpy as np

In [9]:
# Pandas appears to operate in a column-based fashion, but the tomotopy topic_term_dists is naturally arranged by row;
# We can save a bunch of runtime by preparing the DataFrame before sending it off to pyLDAvis, since there are way more columns than there are rows
# (There are as many columns as terms, but only as many rows as topics)

# By default Pandas thinks the DataFrame is a single column, but it's really a single row, so we Transpose
topic_term_dists_rows = [pd.DataFrame(model.get_topic_word_dist(k)).T for k in range(model.k)]
topic_term_dists = pd.concat(topic_term_dists_rows, ignore_index=True)

In [10]:
def _df_with_names(data, index_name, columns_name):
   if type(data) == pd.DataFrame:
      # we want our index to be numbered
      df = pd.DataFrame(data.values)
   else:
      df = pd.DataFrame.from_records(data)
   df.index.name = index_name
   df.columns.name = columns_name
   return df


def _series_with_name(data, name):
   if type(data) == pd.Series:
      data.name = name
      # ensures a numeric index
      return data.reset_index()[name]
   else:
      return pd.Series(data, name=name)

In [11]:
doc_topic_dists

[array([4.7943108e-02, 2.8004700e-01, 9.6551979e-05, 1.7449734e-01,
        5.8377013e-02, 4.3903583e-01], dtype=float32),
 array([5.2017428e-02, 6.2989318e-01, 2.0373959e-04, 2.5395647e-01,
        2.2720729e-04, 6.3679598e-02], dtype=float32),
 array([2.1305590e-04, 1.5574545e-01, 2.6528792e-02, 3.5829768e-01,
        4.5904425e-01, 1.7217365e-04], dtype=float32),
 array([9.7876200e-03, 3.0227832e-02, 8.1370312e-01, 9.4109565e-02,
        4.5355944e-05, 5.2114535e-02], dtype=float32),
 array([9.1847634e-01, 1.6483834e-02, 2.6942021e-04, 6.4236760e-02,
        3.0074379e-04, 2.3272393e-04], dtype=float32),
 array([0.03155842, 0.00084973, 0.13632727, 0.32762668, 0.4641575 ,
        0.03944001], dtype=float32),
 array([1.1247903e-04, 1.2641431e-01, 7.0883614e-01, 1.2716088e-01,
        6.7676809e-03, 3.0721065e-02], dtype=float32),
 array([2.0071681e-04, 1.8914568e-01, 2.1794516e-01, 2.4610810e-01,
        1.7629299e-02, 3.2896006e-01], dtype=float32),
 array([8.9538270e-01, 9.3153981e-

In [12]:
topic_term_dists = _df_with_names(topic_term_dists, 'topic', 'term')
doc_topic_dists  = _df_with_names(doc_topic_dists, 'doc', 'topic')
term_frequency   = _series_with_name(term_frequency, 'term_frequency')
doc_lengths      = _series_with_name(doc_lengths, 'doc_length')
vocab            = _series_with_name(vocab, 'vocab')
R = min(30, len(vocab))
lambda_step = 0.1
n_jobs = -1

In [13]:
%%timeit
topic_freq       = (doc_topic_dists.T * doc_lengths).T.sum()

1.45 ms ± 201 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
topic_freq       = (doc_topic_dists.T * doc_lengths).T.sum()
topic_freq

topic
0    120218.846312
1    180322.056886
2    126002.886138
3    159007.891676
4     99766.305626
5     82975.653293
dtype: float64

In [15]:
topic_freq       = (doc_topic_dists.T * doc_lengths).T.sum()
# topic_freq       = np.dot(doc_topic_dists.T, doc_lengths)
topic_proportion = (topic_freq / topic_freq.sum())

topic_order      = topic_proportion.index
# reorder all data based on new ordering of topics
topic_freq       = topic_freq[topic_order]
topic_term_dists = topic_term_dists.iloc[topic_order]
doc_topic_dists  = doc_topic_dists[topic_order]

# token counts for each term-topic combination (widths of red bars)
term_topic_freq = (topic_term_dists.T * topic_freq).T
## Quick fix for red bar width bug.  We calculate the
## term frequencies internally, using the topic term distributions and the
## topic frequencies, rather than using the user-supplied term frequencies.
## For a detailed discussion, see: https://github.com/cpsievert/LDAvis/pull/41
term_frequency = np.sum(term_topic_freq, axis=0)

In [16]:
from joblib import Parallel, delayed, cpu_count

def _job_chunks(l, n_jobs):
   n_chunks = n_jobs
   if n_jobs < 0:
      # so, have n chunks if we are using all n cores/cpus
      n_chunks = cpu_count() + 1 - n_jobs

   return _chunks(l, n_chunks)

def _chunks(l, n):
    """ Yield successive n-sized chunks from l.
    """
    for i in range(0, len(l), n):
        yield l[i:i+n]
        
def _find_relevance(log_ttd, log_lift, R, lambda_):
   relevance = lambda_ * log_ttd + (1 - lambda_) * log_lift
   return relevance.T.apply(lambda s: s.sort_values(ascending=False).index).head(R)


def _find_relevance_chunks(log_ttd, log_lift, R, lambda_seq):
   return pd.concat([_find_relevance(log_ttd, log_lift, R, l) for l in lambda_seq])

In [17]:
import time
start_time = time.perf_counter()

# marginal distribution over terms (width of blue bars)
term_proportion = term_frequency / term_frequency.sum()

# compute the distinctiveness and saliency of the terms:
# this determines the R terms that are displayed when no topic is selected
topic_given_term = topic_term_dists / topic_term_dists.sum()
kernel = (topic_given_term * np.log((topic_given_term.T / topic_proportion).T))
distinctiveness = kernel.sum()
saliency = term_proportion * distinctiveness

elapsed = time.perf_counter() - start_time
print(f"distinctiveness/saliency calcs {elapsed:.3f}s")
start_time = time.perf_counter()

# Order the terms for the "default" view by decreasing saliency:
default_term_info  = pd.DataFrame({'saliency': saliency, 'Term': vocab, \
                                  'Freq': term_frequency, 'Total': term_frequency, \
                                  'Category': 'Default'}). \
  sort_values(by='saliency', ascending=False). \
  head(R).drop('saliency', 1)
# Rounding Freq and Total to integer values to match LDAvis code:
default_term_info['Freq'] = np.floor(default_term_info['Freq'])
default_term_info['Total'] = np.floor(default_term_info['Total'])
ranks = np.arange(R, 0, -1)
default_term_info['logprob'] = default_term_info['loglift'] = ranks

elapsed = time.perf_counter() - start_time
print(f"Ordering stuff {elapsed:.3f}s")
start_time = time.perf_counter()

## compute relevance and top terms for each topic
log_lift = np.log(topic_term_dists / term_proportion)
log_ttd = np.log(topic_term_dists)
lambda_seq = np.arange(0, 1 + lambda_step, lambda_step)

elapsed = time.perf_counter() - start_time
print(f"loglift stuff {elapsed:.3f}s")
start_time = time.perf_counter()

def topic_top_term_df(tup):
  new_topic_id, (original_topic_id, topic_terms) = tup
  term_ix = topic_terms.unique()
  return pd.DataFrame({'Term': vocab[term_ix], \
                       'Freq': term_topic_freq.loc[original_topic_id, term_ix], \
                       'Total': term_frequency[term_ix], \
                       'logprob': log_ttd.loc[original_topic_id, term_ix].round(4), \
                       'loglift': log_lift.loc[original_topic_id, term_ix].round(4), \
                       'Category': 'Topic%d' % new_topic_id})

top_terms = pd.concat(Parallel(n_jobs=n_jobs)(delayed(_find_relevance_chunks)(log_ttd, log_lift, R, ls) \
                                             for ls in _job_chunks(lambda_seq, n_jobs)))
topic_dfs = map(topic_top_term_df, enumerate(top_terms.T.iterrows(), 1))
elapsed = time.perf_counter() - start_time
print(f"concats {elapsed:.3f}s")
start_time = time.perf_counter()
pd.concat([default_term_info] + list(topic_dfs))

distinctiveness/saliency calcs 0.016s
Ordering stuff 0.008s
loglift stuff 0.005s
concats 0.723s


C:\Users\zechy.wong.ke\Anaconda3\envs\topic-modelling\lib\site-packages\ipykernel_launcher.py:59: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.



Category         Freq         Term        Total  loglift  logprob
term                                                                  
93    Default   707.000000         film   707.000000  30.0000  30.0000
169   Default   604.000000       mobile   604.000000  29.0000  29.0000
27    Default  1319.000000           mr  1319.000000  28.0000  28.0000
99    Default   709.000000        music   709.000000  27.0000  27.0000
115   Default   647.000000       labour   647.000000  26.0000  26.0000
81    Default   658.000000         best   658.000000  25.0000  25.0000
155   Default   501.000000   technology   501.000000  24.0000  24.0000
96    Default   681.000000          her   681.000000  23.0000  23.0000
156   Default   543.000000        party   543.000000  22.0000  22.0000
271   Default   382.000000          oil   382.000000  21.0000  21.0000
259   Default   350.000000       awards   350.000000  20.0000  20.0000
179   Default   420.000000       growth   420.000000  19.0000  19.0000
185   Default   436.000000      economy   436.000000  18.0000  18.0000
223   Default   405.000000         bank   405.000000  17.0000  17.0000
233   Default   431.000000        phone   431.000000  16.0000  16.0000
88    Default   649.000000         game   649.000000  15.0000  15.0000
221   Default   405.000000        users   405.000000  14.0000  14.0000
488   Default   357.000000        yukos   357.000000  13.0000  13.0000
238   Default   395.000000      digital   395.000000  12.0000  12.0000
72    Default   704.000000   government   704.000000  11.0000  11.0000
112   Default   510.000000       market   510.000000  10.0000  10.0000
118   Default   591.000000        games   591.000000   9.0000   9.0000
186   Default   482.000000     election   482.000000   8.0000   8.0000
312   Default   316.000000        award   316.000000   7.0000   7.0000
269   Default   380.000000     software   380.000000   6.0000   6.0000
206   Default   395.000000     economic   395.000000   5.0000   5.0000
26    Default   966.000000          his   966.000000   4.0000   4.0000
405   Default   321.000000        china   321.000000   3.0000   3.0000
311   Default   314.000000       shares   314.000000   2.0000   2.0000
390   Default   355.000000    broadband   355.000000   1.0000   1.0000
...       ...          ...          ...          ...      ...      ...
2081   Topic6   100.666809       angels   100.688461   2.2254  -6.7145
1766   Topic6    90.686249  documentary    90.707901   2.2254  -6.8189
1846   Topic6    87.658302        dance    87.679955   2.2254  -6.8529
1701   Topic6    87.420242       honour    87.441887   2.2254  -6.8556
1958   Topic6    83.576355      concert    83.598000   2.2254  -6.9005
2124   Topic6    83.103378    musicians    83.125031   2.2254  -6.9062
1838   Topic6    82.139290       artist    82.160942   2.2254  -6.9179
2040   Topic6    80.755539     nominees    80.777184   2.2254  -6.9349
2078   Topic6    80.493912  dollar_baby    80.515556   2.2254  -6.9381
93     Topic6   684.163452         film   707.608887   2.1920  -4.7981
312    Topic6   311.437622        award   316.348663   2.2100  -5.5851
545    Topic6   242.512497         song   245.682556   2.2127  -5.8352
465    Topic6   249.971985         band   267.152985   2.1592  -5.8050
334    Topic6   240.496918        films   282.236298   2.0656  -5.8436
621    Topic6   183.746185        prize   203.239395   2.1248  -6.1127
81     Topic6   463.330933         best   658.055786   1.8748  -5.1879
670    Topic6   157.469421        stars   176.745224   2.1102  -6.2671
366    Topic6   201.812790         star   247.359299   2.0221  -6.0190
927    Topic6   132.757706     ceremony   144.949356   2.1378  -6.4378
99     Topic6   366.315094        music   709.596680   1.5644  -5.4228
96     Topic6   332.230011          her   681.258301   1.5075  -5.5205
136    Topic6   260.647797         show   450.231812   1.6791  -5.7631
687    Topic6   147.498413         love   177.729889   2.0392  -6.3325
641    Topic6   149.713806   